name: Registry push

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/lucienshui/github-actions-test
            lucienshui/github-actions-test
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Debug docker meta
        run: |
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Tags labels: ${{ steps.meta.outputs.labels }}"
          echo "Outputs: ${{ steps.meta.outputs }}"

      - name: Debug github
        run: |
          echo "GITHUB: ${{ toJson(github) }}"

      - name: Debug github event
        run: |
          echo "Event: ${{ toJson(github.event) }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Event ref: ${{ github.ref }}"
          echo "Event sha: ${{ github.sha }}"
          echo "Git repo short sha:"
          git rev-parse --short=7 HEAD
          echo "Short sha: ${{ github.sha[0:7] }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64
